### PR TITLE
Carlos menacho  meca6370

### PR DESCRIPTION
**Pull request by Meca6370**
My Project. Finish and Ready. I HOPE AT LEAST.

### CODE REVIEW

**Comment by code-warrior** [comment]
Remove un-necessary files, such as those created by WebStorm (`.idea`).

**Comment by Meca6370** [comment]
I believe i removed the .idea files. Do i need to make another pull request?

**Comment by code-warrior** [comment]
A new pull request is not needed. Simply sync your repo up w/GitHub once the files are removed.

**Comment by Meca6370** [comment]
hey professor how do I sync up?

**Comment by code-warrior** [comment]
After removing the file, commit it, then push your change.

**Comment by Meca6370** [comment]
Yeah okay thats all done. I've commited and pushed my changes

**Comment by code-warrior** [comment]
`.idea` folder is still present. Submission rejected.

**Pull request closed without merging**
